trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployjob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
- stage: QADevDeploy
  jobs:
  - deployment: QADevDeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev

